# Generated by Django 3.2.4 on 2021-06-17 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
