# Generated by Django 3.2.4 on 2021-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('publish',)},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='sno',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
