# Generated by Django 3.2.4 on 2021-06-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210625_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('timeStamp',)},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='publish',
            new_name='timeStamp',
        ),
    ]
