# Generated by Django 3.2.4 on 2021-06-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
